server:
  port: 9080

spring:
  application:
    name: auth-server
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.hazelcast.HazelcastAutoConfiguration

jwt:
  issuer: Madworks
  # access_token expiration - 5min
  ttl-mills: 300000
  # how often will private/public keys be rotated - 15min
  key-rotation-frequency-mills: 900000
  # when will first rotation occur
  # 0 - immediately at service start
  initial-key-rotation-delay-mills: 20000
  # minimum time to hold lock on distributed task after acquiring
  min-lock-lease-time: 5s
  # maximum time to hold lock on distributed task after acquiring
  max-lock-lease-time: 10s

hazelcast-client:
  # IP addresses of Hazelcast member nodes
  members: 127.0.0.1:5701
