server:
  port: 8090

spring:
  application:
    name: resource-server
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password:
  h2:
    console:
      enabled: true

jwt:
  auth:
    # must be secure protocol
    auth-server-url: http://localhost:9080/auth/public-key
    issuer: Madworks