DROP TABLE IF EXISTS INVENTORY;
CREATE TABLE INVENTORY(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    QUANTITY INT NOT NULL,
    UNIT_PRICE DECIMAL(20, 2) NOT NULL,
    CURRENCY_CODE CHAR(3) NOT NULL
);